version: 2
updates:
  - package-ecosystem: docker
    directory: "/tags/base"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: dev

  - package-ecosystem: docker
    directory: "/tags/slim"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: dev

  - package-ecosystem: docker
    directory: "/tags/alpine"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: dev

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: weekly
      time: "06:00"
    target-branch: dev