name: 'Get Data'
description: 'Get Version, Etebase REF and List of Tags'
inputs:
  flavour:
    description: 'Tag flavour'
    required: false
outputs:
  version: 
    description: "Version of the Image"
    value: ${{ steps.get_data.outputs.version }}
  tags: 
    description: "List of Tags"
    value: ${{ steps.get_data.outputs.tags }}
runs:
  using: "composite"
  steps: 
    - id: get_data
      env:
        FLAVOUR: ${{ inputs.flavour }}
        ETESYNC_IMG: victorrds/etesync
        ETEBASE_IMG: victorrds/etebase
      shell: bash
      run: |
        VERSION="master"
        ETE_VERSION="master"
        _SUFFIX=""
        TAGS=""

        if [ -z "$FLAVOUR" ]; then
          TAGS="${ETESYNC_IMG}:latest,${ETEBASE_IMG}:latest"
        else
          TAGS="${ETESYNC_IMG}:${FLAVOUR},${ETEBASE_IMG}:${FLAVOUR}"
          _SUFFIX="-${FLAVOUR}"
        fi

        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${TAGS},${ETESYNC_IMG}:${VERSION}${_SUFFIX},${ETEBASE_IMG}:${VERSION}${_SUFFIX}"
          ETE_VERSION="v{VERSION}"
        fi

        echo ::set-output name=version::${VERSION}
        echo ::set-output name=ete_version::${ETE_VERSION}
        echo ::set-output name=tags::${TAGS}