name: 'Get Git Data'
description: 'Get Version from Git Tags'
outputs:
  source_name: 
    description: "Source Name"
    value: ${{ steps.get_git_data.outputs.source_name }}
  source_branch: 
    description: "Source Branch"
    value: ${{ steps.get_git_data.outputs.source_branch }}
  source_tag: 
    description: "Source Tag"
    value: ${{ steps.get_git_data.outputs.source_tag }}
runs:
  using: "composite"
  steps: 
    - id: get_git_data
      shell: bash
      run: |
        echo ::set-output name=source_name::${GITHUB_REF#refs/*/}
        echo ::set-output name=source_branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=source_tag::${GITHUB_REF#refs/tags/}