name: 'Get Etebase and Docker Tags'
description: 'Get Etebase REF and List of Docker Tags'

inputs:
  baseimg:
    description: 'Base image'
    required: true
  version:
    description: 'Determines tag and Etebvase version (if valid version, everything else fallback to master)'
    required: false
    default: 'dev'
  default_tags:
    description: 'Update default tags?'
    required: false
    default: 'false'

outputs:
  tags: 
    description: "List of Tags"
    value: ${{ steps.get_etebase_tags.outputs.tags }}
  ete_version: 
    description: "Version of the Etebase Server"
    value: ${{ steps.get_etebase_tags.outputs.ete_version }}

runs:
  using: "composite"
  steps: 
    - id: get_etebase_tags
      env:
        BASEIMG: ${{ inputs.baseimg }}
        VERSION: ${{ inputs.version }}
        DEFAULT_TAGS: ${{ inputs.default_tags }}
      shell: bash
      run: |
        ETE_VERSION="master"
        _SUFFIX=""
        _TAGS=""

        if [ "$DEFAULT_TAGS" = "true" ]; then
          if [ "$BASEIMG" == "base" ]; then
            _TAGS="DCKR_IMG:latest"
          else
            _TAGS="DCKR_IMG:${BASEIMG}"
            _SUFFIX="-${BASEIMG}"
          fi
        fi

        _TAGS="${_TAGS},DCKR_IMG:${VERSION}${_SUFFIX}"

        if [[ $VERSION =~ ^[0-9]+\.[0-9]+ ]]; then
            ETE_VERSION="v{VERSION}"
        fi

        echo ::set-output name=ete_version::${ETE_VERSION}
        echo ::set-output name=tags::${_TAGS//DCKR_IMG/victorrds\/etebase},${_TAGS//DCKR_IMG/victorrds\/etesync}