name: "Get Server Version"
description: "Load latest version if input is empty or other pre-determined strings "

inputs:
  version:
    description: "Version Override"
    required: false

outputs:
  version:
    description: "Version of the Server"
    value: ${{ steps.get_version_file.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: get_version_file
      shell: bash
      env:
        OVERRIDE: ${{ inputs.version }}
      run: |
        if [ -z "${OVERRIDE}" ] || [ "${OVERRIDE}" = "latest" ] || [ "${OVERRIDE}" = "stable" ] ; then
          source ./server_version
        else
          ETESYNC_VERSION="${OVERRIDE}"
        fi

        echo "*Version*: ${ETESYNC_VERSION}" >> $GITHUB_STEP_SUMMARY
        echo "version=${ETESYNC_VERSION}" >> $GITHUB_OUTPUT