
---
name: Create Release
on:
  workflow_call:
    inputs:
      version:
        description: "EteBase Version"
        required: true
        type: string

jobs:
  releases-only:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v4

      - id: process_version
        name: Process Version data
        uses: ./.github/actions/process-version
        with:
          version: ${{ inputs.version }}

      - id: create_release
        name: Create Release
        if: ${{ steps.process_version.outputs.is_semver == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          replacesArtifacts: true
          commit: ${{ github.sha }}
          name: "${{ steps.process_version.outputs.version }}"
          generateReleaseNotes: true
          prerelease: false
          tag: ${{ steps.process_version.outputs.version }}
