---
name: PR Build

on:
  workflow_call:
    inputs:
      flavor:
        description: "Set the base image [base, slim or alpine]"
        default: "base"
        required: false
        type: string
      version:
        description: "EteBase Version"
        required: true
        type: string

jobs:
  pr-check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v4

      - id: get_version
        name: Get Server Version
        uses: ./.github/actions/get-server-version
        with:
          version: ${{ inputs.version }}

      - id: process_version
        name: Process Version data
        uses: ./.github/actions/process-version
        with:
          version: ${{ steps.get_version.outputs.version }}

      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - id: docker_pr_build
        name: PR Build
        uses: docker/build-push-action@v5.4.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./tags/${{ inputs.flavor }}/Dockerfile
          tags: victorrds/etebase:${{ github.sha }}-${{ inputs.flavor }}
          build-args: ETE_VERSION=${{ steps.process_version.outputs.ete_version }}
          push: false