
---
name: Create Release
on:
  workflow_call:
    inputs:
      version:
        description: "EteBase Version"
        required: true
        type: string

jobs:
  releases-only:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v4

      - id: prepare
        name: Process Inputs
        uses: ./.github/actions/process-inputs
        with:
          ete_version: ${{ inputs.version }}

      - id: create_release
        name: Create Release
        if: ${{ steps.prepare.outputs.is_semver == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          replacesArtifacts: true
          commit: ${{ github.sha }}
          name: "${{ steps.prepare.outputs.version }}.${{ steps.prepare.outputs.source_ref }}+eb.${{ steps.prepare.outputs.ete_num_version }}+py.${{ steps.prepare.outputs.py_version }}"
          generateReleaseNotes: true
          prerelease: false
          tag: ${{ steps.prepare.outputs.version }}
