---
name: Local Test

on: 
  workflow_dispatch:
    inputs:
      baseimg:
        description: 'Set the base image [base, slim or alpine]'
        required: false
        default: 'base'
      version:
        description: 'EteBase Version'
        required: false
        default: 'dev'
      platforms:
        description: 'Set the platforms to build [ linux/amd64, linux/arm64, linux/arm/v7 or linux/arm/v6]'
        required: false
        default: 'amd64'
      pushit:
        description: 'Should push?'
        required: false
        default: 'false'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v2

      - id: get_labels
        uses: ./.github/actions/get-labels
        with:
          title: 'Etebase Server'
          authors: 'Victor R. Santos <victor-rds@users.noreply.github.com>'
          version: ${{ github.event.inputs.version }}-${{ github.event.inputs.baseimg }}

      - id: get_etebase_tags
        uses: ./.github/actions/get-etebase-tags
        with:
          baseimg: ${{ github.event.inputs.baseimg }}
          version: ${{ github.event.inputs.version }}
          default_tags: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        if: ${{ github.event.inputs.pushit }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Test Build
        id: docker_build_push
        uses: docker/build-push-action@v2.6.1
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ github.event.inputs.platforms }}
          context: .
          file: ./tags/${{ github.event.inputs.baseimg }}/Dockerfile
          build-args: ETE_VERSION=${{ steps.get_etebase_tags.outputs.ete_version }}
          tags: ${{ steps.get_etebase_tags.outputs.tags }}
          push: ${{ toJSON( github.event.inputs.pushit || false ) }}