---
name: Manual Build - Sigle Flavor

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Base image"
        default: "base"
        required: false
        type: choice
        options:
          - "base"
          - "slim"
          - "alpine"
      version:
        description: "EteBase Version"
        required: false
        default: ""
        type: string
      platforms:
        description: "Platforms to build"
        required: false
        default: "linux/amd64,linux/arm64,linux/arm/v7"
        type: choice
        options:
          - "linux/amd64,linux/arm64,linux/arm/v7"
          - "linux/amd64"
          - "linux/arm64,linux/arm/v7"
          - "linux/arm64"
          - "linux/arm/v7" 
      pushit:
        description: "Should push?"
        required: false
        default: false
        type: boolean
      tag:
        description: "Custom Tag"
        required: false
        default: ""
        type: string

jobs:
  manual-build:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: ${{ github.event.inputs.flavor }}
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      dckr_username: ${{ secrets.DOCKER_USER }}
      dckr_token: ${{ secrets.DOCKER_TOKEN }}
