---
name: Test Pull Request changes to Context

on:
  pull_request:
    branches:
      - master
    paths:
      - "context/**"

jobs:
  pr-context-base:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "base"
      version: "master"

  pr-context-slim:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "slim"
      version: "master"

  pr-context-alpine:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "alpine"
      version: "master"
