---
name: (Pull Request) Check changes to Context

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
    paths:
      - "context/**"

permissions:
  contents: read

jobs:
  pr-shell-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}