---
name: (Pull Request) Check Base images builds

on:
  pull_request:
    branches:
      - master
    paths:
      - "tags/base/Dockerfile"

jobs:
  pr-dckr-base-stable:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "base"

  pr-dckr-base-master:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "base"
      version: "master"
