---
name: (Pull Request) Check Base images builds

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
    paths:
      - "tags/base/Dockerfile"

jobs:
  pr-dckr-base:
    strategy:
      matrix:
        version: [ "stable", "master" ]
    uses: ./.github/workflows/call_pr_build.yml
    with:
      flavor: "base"
      version: ${{ matrix.version }}
