---
name: (Pull Request) Check Slim images builds

on:
  pull_request:
    branches:
      - master
    paths:
      - "tags/slim/Dockerfile"

jobs:
  pr-dckr-slim-stable:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "slim"

  pr-dckr-slim-master:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "slim"
      version: "master"
