---
name: (Pull Request) Check Alpine images builds

on:
  pull_request:
    branches:
      - master
    paths:
      - "tags/alpine/Dockerfile"

jobs:
  pr-dckr-alpine-stable:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "alpine"

  pr-dckr-alpine-master:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "alpine"
      version: "master"
