---
name: (Pull Request) Check Alpine images builds

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
    paths:
      - "tags/alpine/Dockerfile"

jobs:
  pr-dckr-alpine:
    strategy:
      matrix:
        version: [ "stable", "master" ]
    uses: ./.github/workflows/call_pr_build.yml
    with:
      flavor: "alpine"
      version: ${{ matrix.version }}
