---
name: (Pull Request) Check new Etebase versions

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
    paths:
      - "server_version"

jobs:
  pr-version:
    uses: ./.github/workflows/call_pr_build.yml
    strategy:
      matrix:
        flavor: [ "base", "slim", "alpine" ]
    with:
      flavor: ${{ matrix.flavor }}
