---
name: (Pull Request) Check new Etebase versions

on:
  pull_request:
    branches:
      - master
    paths:
      - "server_version"

jobs:
  pr-version-base:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "base"

  pr-version-slim:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "slim"

  pr-version-alpine:
    uses: ./.github/workflows/call_pr_check_build.yml
    with:
      flavor: "alpine"

