---
name: Trigger Builds

on:
  workflow_dispatch:
    inputs:
      version:
        description: "EteBase Version"
        required: false
        default: ""
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        required: false
        default: "linux/amd64,linux/arm64,linux/arm/v7"
      pushit:
        description: "Should push?"
        required: false
        default: "false"
      tag:
        description: "Tag"
        required: true
        default: ""

jobs:
  base-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "base"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}

  slim-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "slim"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}

  alpine-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "alpine"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}