---
name: Manual All Flavor Builds

on:
  workflow_dispatch:
    inputs:
      version:
        description: "EteBase Version"
        required: false
        default: ""
        type: string
      platforms:
        description: "Platforms to build"
        required: false
        default: "linux/amd64,linux/arm64,linux/arm/v7"
        type: choice
        options:
          - "linux/amd64,linux/arm64,linux/arm/v7"
          - "linux/amd64"
          - "linux/arm64,linux/arm/v7"
          - "linux/arm64"
          - "linux/arm/v7"
      pushit:
        description: "Should push?"
        required: false
        default: false
        type: boolean
      tag:
        description: "Custom Tag"
        required: false
        default: ""
        type: string

jobs:
  base-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "base"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      dckr_username: ${{ secrets.DOCKER_USER }}
      dckr_token: ${{ secrets.DOCKER_TOKEN }}

  slim-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "slim"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      dckr_username: ${{ secrets.DOCKER_USER }}
      dckr_token: ${{ secrets.DOCKER_TOKEN }}

  alpine-manual:
    uses: ./.github/workflows/call_build_push.yml
    with:
      flavor: "alpine"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      dckr_username: ${{ secrets.DOCKER_USER }}
      dckr_token: ${{ secrets.DOCKER_TOKEN }}