---
name: Trigger New Versions Builds

on:
  push:
    branches:
      - release
    paths:
      - "server_version"

jobs:
  prepare-new-version:
    runs-on: ubuntu-latest
    outputs:
      ete_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Version and Workflow files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            server_version
            ./.github/actions
      - id: get_version
        name: Get Server Version
        uses: ./.github/actions/get-server-version

  new-version:
    needs: prepare-new-version
    uses: ./.github/workflows/call_build_push.yml
    strategy:
      matrix:
        flavor: [ "base", "slim", "alpine" ]
    with:
      flavor: ${{ matrix.flavor }}
      version: ${{ needs.prepare-new-version.outputs.ete_version }}
      pushit: true
    secrets:
      dckr_username: ${{ secrets.DOCKER_USER }}
      dckr_token: ${{ secrets.DOCKER_TOKEN }}

  create-releases:
    needs: [ prepare-new-version, new-version ]
    uses: ./.github/workflows/call_release.yml
    with:
      version: ${{ needs.prepare-new-version.outputs.ete_version }}