---
name: Trigger Workflow Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: "EteBase Version"
        required: false
        type: string
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
        required: false
        type: string
      tag:
        description: "Tag"
        required: false
        type: string
      pushit:
        description: "Should push?"
        default: false
        required: false
        type: boolean

jobs:
  test-base-workflow:
    uses: ./.github/workflows/call_test_metadata.yml
    with:
      flavor: "base"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      tag: ${{ github.event.inputs.tag }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}

  test-slim-workflow:
    uses: ./.github/workflows/call_test_metadata.yml
    with:
      flavor: "slim"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      tag: ${{ github.event.inputs.tag }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}

  test-alpine-workflow:
    uses: ./.github/workflows/call_test_metadata.yml
    with:
      flavor: "alpine"
      version: ${{ github.event.inputs.version }}
      platforms: ${{ github.event.inputs.platforms }}
      tag: ${{ github.event.inputs.tag }}
      pushit: ${{ github.event.inputs.pushit == 'true' }}

  test-releases:
    if: ${{ github.event.inputs.pushit == 'true' }}
    needs: [test-base-workflow, test-slim-workflow, test-alpine-workflow]
    uses: ./.github/workflows/call_release.yml
    with:
      version: ${{ github.event.inputs.version }}