---
name: (Test) Metadata Actions for Dispatch Build

on:
  workflow_dispatch:
    inputs:
      flavors:
        description: "Base images"
        default: '[ "base", "slim", "alpine" ]'
        required: false
        type: choice
        options:
          - '[ "base", "slim", "alpine" ]'
          - '[ "base", "slim" ]'
          - '[ "base", "alpine" ]'
          - '[ "slim", "alpine" ]'
          - '[ "base" ]'
          - '[ "slim" ]'
          - '[ "alpine" ]'
      version:
        description: "EteBase Version"
        required: false
        type: string
      platforms:
        description: "Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
        required: false
        type: string
      tag:
        description: "Tag"
        required: false
        type: string
      pushit:
        description: "Should push?"
        default: false
        required: false
        type: boolean

jobs:
  test-get-version:
    runs-on: ubuntu-latest
    outputs:
      ete_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Version and Workflow files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            server_version
            ./.github/actions/get-server-version
          sparse-checkout-cone-mode: false

      - id: get_version
        name: Get Server Version
        uses: ./.github/actions/get-server-version
        with:
          version: ${{ github.event.inputs.version }}

      - id: show_input
        run: |
          echo '########## inputs ##########'
          echo "flavor: ${{ github.event.inputs.flavors }}"
          echo "version: ${{ github.event.inputs.version }}"
          echo "platforms: ${{ github.event.inputs.platforms }}"
          echo "tag: ${{ github.event.inputs.tag }}"
          echo "pushit: ${{ github.event.inputs.pushit }}"

          echo '########## ete-version ##########'
          echo "ete-version: ${{ steps.get_version.outputs.version }}"

  test-generate-metadata:
    needs: test-get-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ${{ fromJson(github.event.inputs.flavors) }}
    steps:
      - id: checkout
        name: Checkout Dockerfiles and Context
        uses: actions/checkout@v4

      - id: prepare
        name: Process Inputs
        uses: ./.github/actions/process-inputs
        with:
          ete_version: ${{ needs.test-get-version.outputs.ete_version }}
          flavor: ${{ matrix.flavor }}

      - id: docker_metadata
        name: Prepare Docker Metadata
        uses: docker/metadata-action@v5.5.1
        with:
          labels: |
            maintainer=${{ github.repository_owner }}
            version=${{ steps.prepare.outputs.source_ref }}+eb.${{ steps.prepare.outputs.ete_num_version }}+py.${{ steps.prepare.outputs.py_version }}
            org.opencontainers.image.authors=Victor R. Santos <victor-rds@users.noreply.github.com>
            org.opencontainers.image.title=Docker Etebase Server
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.prepare.outputs.ete_version }}
            org.opencontainers.image.base.name=docker.io/library/${{ steps.prepare.outputs.py_image }}
            org.opencontainers.image.url=https://hub.docker.com/r/${{ secrets.dckr_username }}/etebase
          images: |
            ${{ secrets.dckr_username }}/etebase
            ${{ secrets.dckr_username }}/etesync
          flavor: |
            latest=${{ ( matrix.flavor == 'base' && steps.prepare.outputs.is_semver == 'true' ) }}
            suffix=${{ steps.prepare.outputs.suffix }}
          tags: |
            type=edge,enable=${{ inputs.tag != '' || steps.prepare.outputs.is_semver == 'false' }}
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
            type=raw,value=${{ matrix.flavor }},suffix=,enable=${{ inputs.tag == '' && steps.prepare.outputs.is_semver == 'true' }}
            type=semver,pattern={{version}},value=${{ steps.prepare.outputs.ete_version }},enable=${{ inputs.tag == '' && steps.prepare.outputs.is_semver == 'true' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.prepare.outputs.ete_version }},enable=${{ inputs.tag == '' && steps.prepare.outputs.is_semver == 'true' }}

      - name: Metadata Output
        shell: bash
        run: |
          echo "flavor: ${{ matrix.flavor }}"

          echo '########## prepare ##########'
          echo "suffix: ${{ steps.prepare.outputs.suffix }}"
          echo "semver: ${{ steps.prepare.outputs.is_semver }}"
          echo "ete_version: ${{ steps.prepare.outputs.ete_version }}"
          echo "ete_version (num only): ${{ steps.prepare.outputs.ete_num_version }}"
          echo "py_image: ${{ steps.prepare.outputs.py_image }}"
          echo "py_version: ${{ steps.prepare.outputs.py_version }}"
          echo "source_ref: ${{ steps.prepare.outputs.source_ref }}"

          echo '########## docker_metadata ##########'
          echo "${{ steps.docker_metadata.outputs.tags }}"
          echo "${{ steps.docker_metadata.outputs.labels }}"